//
// Generated by LLVM NVPTX Back-End
//

.version 6.3
.target sm_70
.address_size 64

	// .globl	__kmpc_get_hardware_thread_id_in_block
.weak .global .align 8 .b8 __omp_rtl_device_memory_pool[16];
.weak .global .align 8 .b8 __omp_rtl_device_memory_pool_tracker[32];
.weak .global .align 4 .u32 __omp_rtl_debug_kind;
.weak .global .align 4 .u32 __omp_rtl_assume_no_thread_state;
.weak .global .align 4 .u32 __omp_rtl_assume_no_nested_parallelism;
.weak .const .align 8 .b8 __omp_rtl_device_environment[48];

.visible .func  (.param .b32 func_retval0) __kmpc_get_hardware_thread_id_in_block()
{
	.reg .b32 	%r<2>;

	mov.u32 	%r1, %tid.x;
	st.param.b32 	[func_retval0+0], %r1;
	ret;

}
	// .globl	__kmpc_barrier_simple_spmd
.visible .func __kmpc_barrier_simple_spmd(
	.param .b64 __kmpc_barrier_simple_spmd_param_0,
	.param .b32 __kmpc_barrier_simple_spmd_param_1
)
{


	bar.sync 	0;
	ret;

}
